language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "adilsonsilva-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_KEY" # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  #- sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

#-- nova configuração docker e heroku

services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH&amp;amp;amp;amp;amp;amp;amp;lt;span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start"&amp;amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;amp;lt;/span&amp;amp;amp;amp;amp;amp;amp;gt;; fi`
- export IMAGE_NAME=adilsonsilva86/autenticacao
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: freelancer-kit
