language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "adilsonsilva-github" # the key of the org you chose at step #3
    token:
      secure: "cd9f2b854966de4ae5fa861264cc4dc0d7abfa63" # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  #- sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

#-- nova configuração docker e heroku

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "c937a2d5-457b-4c68-a1bb-df9227f0c5dc" | docker login -u "adilson.ro.silva@gmail.com" --password-stdin registry.heroku.com

install:
  # install deps
  - yarn install

script:
  - yarn test
  - yarn build
  # build docker images
  - docker build -t adilsonsilva86/autenticacao .
  - docker tag adilsonsilva86/autenticacao registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script: 
    # push to dockerhub & heroku
    docker push adilsonsilva86/autenticacao;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master
